### ISSUE TITLE
Listen to event without parameters in code

### ISSUE THREAD

**Issue by Mattias-TB** [chark/scriptable-events#25]
I am trying to listen to an event in code and have tried reading the section "Manually Subscribing to Events" in the documentation, but I do not understand how I can listen to events without any parameters.

I have tried like this, but it seems like the method called needs to have a `SimpleArg` parameter specified.
`[SerializeField] private SimpleScriptableEvent playerJumpedEvent;`

Is it possible to listen to events without parameters?

**Comment by Edvinas01** [comment]
Hey, indeed the `SimpleScriptableEvent` type requires an argument, however its a singleton which cannot be instantiated manually. This approach is chosen so the same base type could be used for all events and so that this one exception for an arg-less event type could be avoided and will most likely stay this way.

Having said that, you can use this event type like this in your case:
```cs
[SerializeField] private SimpleScriptableEvent playerJumpedEvent;

...

private void OnEnable()
{
    playerJumpedEvent.AddListener(OnPlayerJumped);
}

private void OnDisable()
{
    playerJumpedEvent.RemoveListener(OnPlayerJumped);
}

private void OnPlayerJumped(SimpleArg arg)
{
    // Handle event here...
}
```

**Comment by Mattias-TB** [comment]
Thank you! I had tried it that way, but was not sure if it was the correct way.

Is there anything useful that is passed to the listener function in the SimpleArg?

You can close this if you like, it answers my question, thank you again! 👍

**Comment by Edvinas01** [comment]
`SimpleArg` is just an empty class (it doesn't have any information in it and is just used to simplify the API), so it can be ignored in the listener.
